name: scraping
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - expat=2.6.4
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.13.1
  - python_abi=3.13
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - idna==3.10
      - lxml==5.3.0
      - requests==2.32.3
      - soupsieve==2.6
      - urllib3==2.3.0
